"""empty message

Revision ID: 288390b8367b
Revises: 34f2334e9939
Create Date: 2021-04-21 09:32:40.040162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288390b8367b'
down_revision = '34f2334e9939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newtopic_post',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_newtopic_post_timestamp'), 'newtopic_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newtopic_post_timestamp'), table_name='newtopic_post')
    op.drop_table('newtopic_post')
    # ### end Alembic commands ###
