"""empty message

Revision ID: 36b6501332e2
Revises: 288390b8367b
Create Date: 2021-04-27 23:07:15.576857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b6501332e2'
down_revision = '288390b8367b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('rendered_data', sa.Text(), nullable=False),
    sa.Column('pic_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newtopic',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_newtopic_timestamp'), 'newtopic', ['timestamp'], unique=False)
    op.drop_index('ix_newtopic_post_timestamp', table_name='newtopic_post')
    op.drop_table('newtopic_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newtopic_post',
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=20), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('post', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index('ix_newtopic_post_timestamp', 'newtopic_post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_newtopic_timestamp'), table_name='newtopic')
    op.drop_table('newtopic')
    op.drop_table('phone')
    op.drop_table('ads')
    # ### end Alembic commands ###
